/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TunerRouteImport } from './routes/tuner'
import { Route as MetronomeRouteImport } from './routes/metronome'
import { Route as ChordsRouteImport } from './routes/chords'
import { Route as IndexRouteImport } from './routes/index'

const TunerRoute = TunerRouteImport.update({
  id: '/tuner',
  path: '/tuner',
  getParentRoute: () => rootRouteImport,
} as any)
const MetronomeRoute = MetronomeRouteImport.update({
  id: '/metronome',
  path: '/metronome',
  getParentRoute: () => rootRouteImport,
} as any)
const ChordsRoute = ChordsRouteImport.update({
  id: '/chords',
  path: '/chords',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chords': typeof ChordsRoute
  '/metronome': typeof MetronomeRoute
  '/tuner': typeof TunerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chords': typeof ChordsRoute
  '/metronome': typeof MetronomeRoute
  '/tuner': typeof TunerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chords': typeof ChordsRoute
  '/metronome': typeof MetronomeRoute
  '/tuner': typeof TunerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chords' | '/metronome' | '/tuner'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chords' | '/metronome' | '/tuner'
  id: '__root__' | '/' | '/chords' | '/metronome' | '/tuner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChordsRoute: typeof ChordsRoute
  MetronomeRoute: typeof MetronomeRoute
  TunerRoute: typeof TunerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tuner': {
      id: '/tuner'
      path: '/tuner'
      fullPath: '/tuner'
      preLoaderRoute: typeof TunerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metronome': {
      id: '/metronome'
      path: '/metronome'
      fullPath: '/metronome'
      preLoaderRoute: typeof MetronomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chords': {
      id: '/chords'
      path: '/chords'
      fullPath: '/chords'
      preLoaderRoute: typeof ChordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChordsRoute: ChordsRoute,
  MetronomeRoute: MetronomeRoute,
  TunerRoute: TunerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
